version: '3.8'
services:
  ss_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ss_backend
    restart: unless-stopped
    volumes:
      - "./:/root/app"
    env_file: .env
    network_mode: host
  ss_nginx:
    image: nginx:alpine
    container_name: ss_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certs/:/root/cert/
    network_mode: host