version: '3.8'
services:
  ss_backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: ss_backend
    restart: unless-stopped
    volumes:
      - "./:/root/app"
    network_mode: host