version: '3.8'
services:
  ss_pg:
    image: postgres:13-alpine
    container_name: ss_pg
    restart: unless-stopped
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432