version: '3.8'
services:
  ss_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ss_backend
    restart: unless-stopped
    volumes:
      - "/app/node_modules"
      - "./:/app"
    network_mode: host